#int(): constructs an integer number from an integer literal, afloat literal(removing all decimals),or a string literal (providing the string represents a whole number)
#float(): constructs a float number from an integer literal, a float literal or a string literal (providing the string represents a float or an integer)  
#str() - constructs a string from a wide variety of data types, including strings, integer literals and float literals

print("example of int()")
x=int(1)
y=int(2.4)
z=int("3")
print(x)
print(y)
print(z)

print("example of str()")
a=str(1)
b=str(2.5)
c=str("s1")
print(a)
print(b)
print(c)

print("example of float()")
d=float(1)
e=float(2.7)
f=float("2.9")
g=float("3.0")
print(d)
print(e)
print(f)
print(g)